# Generated by Django 3.2.4 on 2024-07-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.SlugField(max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
