# Generated by Django 3.2.4 on 2024-07-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('year', models.DateField()),
                ('director', models.CharField(blank=True, max_length=255)),
                ('actors', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(default='../clapper_board_vector_oi5zxv', upload_to='images/')),
                ('genre', models.ManyToManyField(default=1, related_name='movies', to='genres.Genre')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
